project:
  type: website
  output-dir: docs

website:
  title: "The Monash University Press"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tdew0002

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "Outline"
    toc-depth: 2




