{
  "hash": "a3f83e2b57e62abf2178d548aa651409",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Fluctuation of Melbourne Temperature 2022-2024\"\nauthor: \"Tycia Dewi\"\ndate: \"2024-10-1\"\ncategories: [Article, Code, Report]\n---\n\n\n![](thumbnail.jpg)\n\n\n::: {.cell}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n# Four Seasons in a Day: The Lore of Melbourne’s Weather\n\nAs seen in the TikTok post below, Melbourne’s weather is notorious for being erratic, changing as quickly as the blink of an eye from sunshine to rain, freezing cold to warm, or all of these in a day; the “four seasons in a day” phenomenon. In the past two years, these fluctuations have been seen to occur more frequently with less accurate weather forecasts (Attanasjo, 2024; Newswire, 2023; King et al., 2024). Why is this?\n\n::: {style=\"max-width: 605px;\"}\n<iframe src=\"https://www.tiktok.com/embed/v2/7306808019055152385\" width=\"605\" height=\"590\" frameborder=\"0\" allowfullscreen>\n\n</iframe>\n:::\n\n## The Data for the Investigation\n\n### Where to get the data?\n\nTo investigate this weather fluctuation further in the last two years, I gathered data from the Australian Government Bureau of Meteorology website [here](http://www.bom.gov.au/), for weather reports in the Melbourne area near Olympic Park, which is relatively a more central area.\n\nThe two main datasets I collected were:\n\n-   The minimum temperature data [here](https://reg.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode=123&p_display_type=dailyDataFile&p_startYear=&p_c=&p_stn_num=086338).\n\n-   The maximum temperature data [here](https://reg.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode=122&p_display_type=dailyDataFile&p_startYear=&p_c=&p_stn_num=086338).\n\n### What is inside the data?\n\nThe original data downloaded has 8 Variables:\n\n-   `Product Code` : Identifies the specific dataset or type of weather data being reported, in this case, IDCJAC0011.\n\n-   `Bureau of Meteorology station number` :A unique identifier for the weather observation station where the data was collected, such as station number 86338.\n\n-   `Year` :The year the data was recorded, for example, 2023.\n\n-   `Month` :The month of the year when the weather data was recorded.\n\n-   `Day` :The specific day of the month when the weather data was recorded.\n\n-   `Maximum temperature (Degree C)` or `Minimum temperature (Degree C)`:The highest or lowest temperature recorded for the day in degrees Celsius.\n\n-   `Days of accumulation of maximum temperature` :The number of days over which maximum temperature data has been accumulated or aggregated.\n\n-   `Quality` :A measure of the reliability or accuracy of the recorded data, often indicated by a quality rating or flag.\n\n### How do we process the data?\n\n-   Download all the available data for both the maximum and minimum temperature for Melbourne (Olympic Park) station, for all years beginning from 2013 to date.\n-   Merge the minimum temperature data with the maximum temperature dataset by `Year`, `Month`, `Day` and `Quality`.\n-   Tidy up the data by renaming variables into a tidy format using janitor and removing NAs. Combine the “day/month/year” variable into a new variable called date in format: “%Y-%m-%d”, for filtering purposes.\n-   Filter data from 1-Sep-2022 until 31-Aug-2024 to get exactly 2 years worth of data.\n-   Transform the data into a longer format and separating type_temperature into 6 types, where these different types of temperature will the stored in variable: `minimum_temperature_degree_c_2022`, `maximum_temperature_degree_c_2022`, `minimum_temperature_degree_c_2023`, `maximum_temperature_degree_c_2023`, `minimum_temperature_degree_c_2024` and `maximum_temperature_degree_c_2024`\n-   `variable` is useful for the plot creation for having different lines for each year for minimum and maximum temperature.\n-   The data is ready for the plot making process.\n\n### Code for data cleaning\n\n\n::: {.cell layout-align=\"center\"}\n\n````{.cell-code}\n```{{r cleaning_data}}\nweather_data <- merge(weather_data_min, \n                      weather_data_max, \n                      by = c(\"Year\", \n                             \"Month\", \n                             \"Day\", \n                             \"Quality\")) |> \n  rename_all(janitor::make_clean_names) |>\n  select(year, \n         month, \n         day, \n         minimum_temperature_degree_c, \n         maximum_temperature_degree_c) |>\n  rename(min_temp = minimum_temperature_degree_c, \n         max_temp =maximum_temperature_degree_c) |>\n  mutate(date = as.Date(paste(year, month, day, sep = \"-\"), \n                        format = \"%Y-%m-%d\")) |>\n  filter(date > as.Date(\"2022-08-31\") & date <= as.Date(\"2024-08-31\"))\n\nweather_long <- weather_data |>\n  pivot_longer(cols = c(min_temp, max_temp),\n               names_to = \"variable\",\n               values_to = \"temperature\") |>\n  mutate(variable = paste(variable, \n                          year, \n                          sep = \"_\"))\n```\n````\n:::\n\n\n## A Deep Dive into this Phenomenon\n\n\n::: {#tbl-summary .cell layout-align=\"center\" tbl-cap='Table of Median Minimum and Maximum Temperature in Melbourne per month over September 2022 - August 2024'}\n::: {.cell-output-display}\n\n\n| Year|Month | Median Min Temperature| Median Max Temperature|\n|----:|:-----|----------------------:|----------------------:|\n| 2022|09    |                   9.45|                  16.00|\n| 2022|10    |                  10.30|                  19.00|\n| 2022|11    |                  11.60|                  19.25|\n| 2022|12    |                  12.90|                  23.50|\n| 2023|01    |                  16.30|                  24.20|\n| 2023|02    |                  15.90|                  22.80|\n| 2023|03    |                  14.60|                  21.70|\n| 2023|04    |                  12.00|                  19.25|\n| 2023|05    |                   9.30|                  15.90|\n| 2023|06    |                   8.85|                  15.20|\n| 2023|07    |                   9.60|                  14.80|\n| 2023|08    |                   8.90|                  15.70|\n| 2023|09    |                   9.65|                  20.25|\n| 2023|10    |                  10.30|                  17.50|\n| 2023|11    |                  13.75|                  19.20|\n| 2023|12    |                  14.90|                  23.80|\n| 2024|01    |                  16.40|                  24.20|\n| 2024|02    |                  16.00|                  23.10|\n| 2024|03    |                  14.40|                  22.60|\n| 2024|04    |                  11.20|                  18.50|\n| 2024|05    |                   8.30|                  17.10|\n| 2024|06    |                   7.20|                  13.90|\n| 2024|07    |                   7.70|                  13.10|\n| 2024|08    |                  10.30|                  18.10|\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Line Chart of Minimum and Maximum Temperature in Melbourne by month over September 2022 - August 2024](index_files/figure-html/fig-line-Chart-1.png){#fig-line-Chart fig-align='center' width=100%}\n:::\n:::\n\n\nFrom @fig-line-Chart plot 1 to 3 that the maximum temperatures in 2023 is quite significantly higher than 2024. The highest temperature being 40℃ in 2023. When comparing 2023 to 2022, we can see from graph 12 that 2022 had higher maximum temperatures reaching 38℃. In this case, we can see a trend that the summers had gotten cooler, especially in 2024, compared to the two previous summers (Newswire, 2023). These findings are consistent with @tbl-summary where we can see that the lowest median max temperature is 16℃ in 2022 and 15.2℃ in 2023, while it is 13.1℃ in 2024.\n\nIn terms of winter, plot 6 to 8 shows more frequent dips in temperature in 2024 compared to 2023, as temperatures reached nearly 0℃ on three different occasions. While in 2023, a dip nearing 0℃ occurred only once. As seen on @tbl-summary, the lowest median minimum temperature is 9.45℃ in 2022, 8.85℃ in 2023 and 7.2℃ in 2024. We can see that the pattern is evident with 2024 being the coolest year with lower temperatures compared to the two previous years (Saunders, 2024; Convery & Taylor, 2024).\n\nFrom these observations, it is evident that 2024 had cooler temperatures compared to two previous years. Why is this?\n\nResearchers stated that this inconsistency in weather patterns can be attributed to two major factors Westra et al., 2014; Schmidt, 2023):\n\n-   Climate change\n\n-   Changing relationships between climate drivers including El Niño-Southern Oscillation (ENSO) and Southern Annular Mode (SAM)\n\nClimate change causes irregularities in weather patterns, including causing unsolicited rains on a perfectly sunny day or temperature drops on a warm day (Westra et al., 2014; Schmidt, 2023). This in turn, alters the interactions between climate drivers, while the El Niño was supposed to increase temperatures, the SAM brings cold air from Antarctica to Australia, which helps to cool down the heat (Keenan, 2024). As a result, temperatures have become more unpredictable, leading to increased fluctuations and less accurate weather forecasts\n\n## So, what now?\n\nIn conclusion, we found that the year 2024 is the coolest year in the past two years, with cooler winters and summers, accompanied with more dips in the temperatures during winter (King et al., 2024). Moreover, the frequency of “four seasons in a day” occurring in Melbourne in the past two years can be attributed to climate change, which leads to erratic weather patterns and affects the relationship between climate drivers. While so, with the development of AI and weather forecasting technologies, erratic weather patterns will be more accurately predicted in the future. \n\n## References\n\nKeenan, C. (31 January 2024). Melbourne weathers its first January without a ‘hot’ day since 1984 <https://www.theguardian.com/weather/2024/jan/31/melbourne-weather-forecast-heatwaves-under-35-record>\n\nAttanasjo, J. (18 January 2024). Why Aussie weather forecasts have got it wrong during 'weird' summer <https://au.news.yahoo.com/why-aussie-weather-forecasts-wrong-during-weird-summer-003452203.html>\n\nNewsWire. (25 August 2023). Grim hidden meaning in this image <https://au.sports.yahoo.com/grim-hidden-meaning-image-235700320.html>\n\nKing, A, Reid, K, Barnes, M, & Earl-Jones, N. (12 April 2024). Despite what you might hear, weather prediction is getting better, not worse <https://theconversation.com/despite-what-you-might-hear-weather-prediction-is-getting-better-not-worse-225904>\n\nWestra, S., Fowler, H. J., Evans, J. P., Alexander, L. V., Berg, P., Johnson, F., Kendon, E. J., Lenderink, G., & Roberts, N. M. (2014). Future changes to the intensity and frequency of short-duration extreme rainfall <https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2014RG000464>\n\nSchmidt, S. (20 September 2023). El Niño and La Niña – what’s it all about? <https://www.csiro.au/en/news/all/articles/2023/september/el-nino-la-nina>\n\nSaunders, T. (12 April 2024). BOM's first winter forecast for 2024 declares it could be one of Australia's warmest on record <https://www.abc.net.au/news/2024-04-12/nsw-winter-forecast-one-of-warmest-on-record/103697742#>\n\nConvery, S. & Taylor, J. (2024). Australia’s south-east to endure more wintry weather after Melbourne records coldest day in five years <https://www.theguardian.com/australia-news/article/2024/jun/14/melbourne-records-coldest-day-in-five-years-as-wintry-weather-blankets-australias-south-east>\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}